-- Create storage bucket for insurance documents
INSERT INTO storage.buckets (id, name, public)
VALUES ('insurance-docs', 'insurance-docs', false)
ON CONFLICT (id) DO NOTHING;

-- RLS Policies for insurance-docs
-- Allow authenticated users to upload (Company Admins)
CREATE POLICY "Authenticated users can upload insurance docs"
ON storage.objects FOR INSERT
TO authenticated
WITH CHECK (bucket_id = 'insurance-docs');

-- Allow authenticated users to read (Company Admins)
-- Limiting to own company files is hard in storage RLS without custom metadata or folder structure using company_id.
-- For MVP, we'll allow authenticated reads, or rely on Signed URLs generated by server.
-- If public=false, we MUST use signed URLs. 
-- Policy for "Select" is needed for the server (Service Role bypasses RLS) but if client downloads directly?
-- Let's stick to Signed URLs. No public read access.
CREATE POLICY "Authenticated users can read insurance docs"
ON storage.objects FOR SELECT
TO authenticated
USING (bucket_id = 'insurance-docs');
